name: Push to Client's Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to client's repo
        run: |
          git remote set-url --push client ${{ secrets.CLIENT_REPO_URL }}
          git push client main
